org.gradle.jvmargs=-Xmx2G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true
minecraft_version=1.21.4
minecraft_version_range=[1.21.4]
neo_version=21.4.156
neo_version_range=[21.4, 21.5)
loader_version_range=[4,)
parchment_minecraft_version=1.21.4
parchment_mappings_version=2025.03.23
mod_id=stone_x_iron_chests
mod_name=Stone X Iron Chests
mod_license=GNU GPL 3.0
mod_version=1.21.4-1.3.0
mod_group_id=dev.invalid
mod_authors=vlad0-0
mod_description=This mod adds the Stone Chests to the Iron Chests mod progression.
